#' Generate qc plots from an MS experiment stored as SummarizedExperiment
#'
#' This function generates quality control plots from SummarizedExperiment objects.
#'
#' Plots that can be generated are:
#'
#'  - m/z deviation histogram ("mz_diff")
#'  - retention time deviation histogram ("rt_diff")
#'  - m/z deviation by sample bar plot ("mz_diff_sample")
#'  - retention time deviation by sample bar plot ("rt_diff_sample")
#'  - ion mobility deviation histogram ("ims_diff")
#'  - ion mobility deviation by sample bar plot ("ims_diff_sample")
#'
#' Which plots to generate can be specified using the 'what' argument.
#' Requires per sample "mz", "rt", and/or "ims" assays and corresponding rowData columns.
#' These are all present for SummarizedExperiment objects generated by the default settings of the mzMine_to_se function.
#' Inspired by xcms::plotQC.R
#'
#' @importFrom dplyr %>% mutate select filter group_by summarize_at
#' @importFrom utils read.csv
#' @importFrom SummarizedExperiment SummarizedExperiment assays rowData colData assayNames
#' @importFrom mzReactionMineR se_to_long
#' @importFrom methods setClass new
#' @importFrom grDevices nclass.Sturges
#' @import ggplot2
#' @param object a SummarizedExperiment object
#' @param rt_assay character. The name of the assay containing the per sample retention time values. Default is "rt".
#' @param mz_assay character. The name of the assay containing the per sample m/z values. Default is "mz".
#' @param ims_assay character. The name of the assay containing the per sample ion mobility values. Default is "ims".
#' @param rt_col character. The name of the rowData column containing the reference retention time values. Default is "rt".
#' @param mz_col character. The name of the rowData column containing the reference m/z values. Default is "mz".
#' @param ims_col character. The name of the rowData column containing the reference ion mobility values. Default is "ims".
#' @param filename a character string indicating the name of the column in the colData that corresponds to the assay columns. Default is "filename".
#' @param what Any of "rt_diff", "mz_diff", "rt_diff_sample", "mz_diff_sample", ".ims_diff", or "ims_diff_sample".
#'     What plots to produce.
#' @param print Logical. Whether to print the plots to the current device.
#' @param return_object Logical. Whether to return the intermediary SummarizedExperiment object along with the plots.
#'     Only necessary for testing.
#'
#' @returns a list object of class QCPlots that contains the summarized
#'     experiment and a list of ggplots
#' @export
#'
qc_plots <- function(
    object,
    rt_assay = "rt",
    mz_assay = "mz",
    ims_assay = "ims",
    rt_col = "rt",
    mz_col = "mz",
    ims_col = "ims",
    filename = "filename",
    what = c(
      "rt_diff",
      "mz_diff",
      "rt_diff_sample",
      "mz_diff_sample"
    ),
    print = TRUE,
    return_object = FALSE
){

  object_name <- object_argument_name(substitute(object))

  if(!inherits(object, "SummarizedExperiment")) {
    stop("'", object_name, "' must be a SummarizedExperiment.")
  }

  if(length(what) == 0L || !is.character(what)) {
    stop("'what' must contain at least one plot type.")
  }

  if(!any(what %in% c("rt_diff", "mz_diff", "rt_diff_sample", "mz_diff_sample", "ims_diff", "ims_diff_sample"))) {
    stop("'what' must be any of 'rt_diff', 'mz_diff', 'rt_diff_sample', 'mz_diff_sample', 'ims_diff', or 'ims_diff_sample'.")
  }

  if(any(c("rt_diff", "rt_diff_sample") %in% what) & any(!is.character(rt_assay) ||
     !rt_assay %in% assayNames(object))) {
    stop("'rt_assay' must name an assay in '", object_name, "'.")
  }

  if(any(c("rt_diff", "rt_diff_sample") %in% what) & any(!is.character(rt_col) ||
     !rt_col %in% colnames(rowData(object)))) {
    stop("'rt_col' must be a column in '", object_name, "'.")
  }

  if(any(c("mz_diff", "mz_diff_sample") %in% what) & any(!is.character(mz_assay) ||
     !mz_assay %in% assayNames(object))) {
    stop("'mz_assay' must name an assay in '", object_name, "'.")
  }

  if(any(c("mz_diff", "mz_diff_sample") %in% what) & any(!is.character(mz_col) ||
     !mz_col %in% colnames(rowData(object)))) {
    stop("'mz_col' must be a column in '", object_name, "'.")
  }

  if(any(c("ims_diff", "ims_diff_sample") %in% what) & any(!is.character(ims_assay) ||
     !ims_assay %in% assayNames(object))) {
    stop("'ims_assay' must name an assay in '", object_name, "'.")
  }

  if(any(c("ims_diff", "ims_diff_sample") %in% what) & any(!is.character(ims_col) ||
     !ims_col %in% colnames(rowData(object)))) {
    stop("'ims_col' must be a column in '", object_name, "'.")
  }

  # rt deviation

  if(any(c("rt_diff", "rt_diff_sample") %in% what)){
    assays(object)[["rt_diff"]] <- assays(object)[[rt_assay]] - rowData(object)[[rt_col]]
  }

  # mz deviation

  if(any(c("mz_diff", "mz_diff_sample") %in% what)){
    assays(object)[["mz_diff"]] <- assays(object)[[mz_assay]] - rowData(object)[[mz_col]]
  }

  # ims deviation

  if(any(c("ims_diff", "ims_diff_sample") %in% what)){
    assays(object)[["ims_diff"]] <- assays(object)[[ims_assay]] - rowData(object)[[ims_col]]
  }

  # generate list of specified ggplots

  plots <- list()

  if("mz_diff" %in% what){

    tmp <- se_to_long(object, assay = "mz_diff", filename = filename) %>%
      filter(
        !is.na(.data$value)
      )

    breaks <- pretty(range(tmp$value),
                     n = nclass.Sturges(tmp$value),
                     min.n = 1)

    plots[["mz_diff"]] <- tmp %>%
      ggplot(
        aes(
          x = value
        )
      ) +
      geom_histogram(
        aes(y = after_stat(density)),
        alpha = 0.25,
        fill = "white",
        color = "black",
        breaks = breaks
      ) +
      labs(
        x = "m/z deviation",
        y = "Density",
        title = "m/z deviation"
      ) +
      theme_classic()

    if(print) {
      print(plots[["mz_diff"]])
    }

  }

  if("rt_diff" %in% what){
    tmp <- se_to_long(object, assay = "rt_diff", filename = filename) %>%
      filter(
        !is.na(.data$value)
      )

    breaks <- pretty(range(tmp$value),
                     n = nclass.Sturges(tmp$value),
                     min.n = 1)

    plots[["rt_diff"]] <- tmp %>%
      ggplot(
        aes(
          x = value
        )
      ) +
      geom_histogram(
        aes(y = after_stat(density)),
        alpha = 0.25,
        fill = "white",
        color = "black",
        breaks = breaks
      ) +
      labs(
        x = "rt deviation",
        y = "Density",
        title = "rt deviation"
      ) +
      theme_classic()

    if(print) {
      print(plots[["rt_diff"]])
    }

  }

  if("ims_diff" %in% what){
    tmp <- se_to_long(object, assay = "ims_diff", filename = filename) %>%
      filter(
        !is.na(.data$value)
      )

    breaks <- pretty(range(tmp$value),
                     n = nclass.Sturges(tmp$value),
                     min.n = 1)

    plots[["ims_diff"]] <- tmp %>%
      ggplot(
        aes(
          x = value
        )
      ) +
      geom_histogram(
        aes(y = after_stat(density)),
        alpha = 0.25,
        fill = "white",
        color = "black",
        breaks = breaks
      ) +
      labs(
        x = "ims deviation",
        y = "Density",
        title = "ims deviation"
      ) +
      theme_classic()

    if(print) {
      print(plots[["ims_diff"]])
    }

  }


  if("rt_diff_sample" %in% what){

    plots[["rt_diff_sample"]] <- se_to_long(object, assay = "rt_diff" , filename = filename) %>%
      group_by(
        filename
      ) %>%
      summarize_at(
        "value",
        .funs = list(median),
        na.rm = TRUE
      ) %>%
      ggplot(
        aes(
          x = filename,
          y = value,
          fill = value
        )
      ) +
      geom_col() +
      labs(
        x = "Sample",
        y = "Median rt deviation",
        title = "rt deviation by sample"
      ) +
      scale_fill_viridis_c(option = "cividis") +
      theme_classic() +
      theme(
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank()
      )

    if(print) {
      print(plots[["rt_diff_sample"]])
    }

  }

  if("mz_diff_sample" %in% what){

    plots[["mz_diff_sample"]] <- se_to_long(object, assay = "mz_diff", filename = filename) %>%
      group_by(
        filename
      ) %>%
      summarize_at(
        "value",
        .funs = list(median),
        na.rm = TRUE
      ) %>%
      ggplot(
        aes(
          x = filename,
          y = value,
          fill = value
        )
      ) +
      geom_col() +
      labs(
        x = "Sample",
        y = "Median m/z deviation",
        title = "m/z deviation by sample"
      ) +
      scale_fill_viridis_c(option = "cividis") +
      theme_classic() +
      theme(
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank()
      )

    if(print) {
      print(plots[["mz_diff_sample"]])
    }

  }

  if("ims_diff_sample" %in% what){

    plots[["ims_diff_sample"]] <- se_to_long(object, assay = "ims_diff", filename = filename) %>%
      group_by(
        filename
      ) %>%
      summarize_at(
        "value",
        .funs = list(median),
        na.rm = TRUE
      ) %>%
      ggplot(
        aes(
          x = filename,
          y = value,
          fill = value
        )
      ) +
      geom_col() +
      labs(
        x = "Sample",
        y = "Median ims deviation",
        title = "ims deviation by sample"
      ) +
      scale_fill_viridis_c(option = "cividis") +
      theme_classic() +
      theme(
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank()
      )

    if(print) {
      print(plots[["ims_diff_sample"]])
    }

  }

  # return object

  if(return_object == TRUE){
    return(list(
      se = object,
      plots = plots
    ))
  } else {
    return(plots)
  }

}


utils::globalVariables(c(".data", ".", "..density..", "density", "filename",
                         "value"))
